name: Node.js Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install

    - name: Start-server-and-test preview http://localhost:4173 'cypress run --e2e'
      run: npm test:e2e
    - name: Start-server-and-test 'vite dev --port 4173' http://localhost:4173 'cypress open --e2e'
      run: test:e2e:dev
